language: java
sudo: false

jdk:
  - openjdk7
  - oraclejdk8

# only build master and the MATH_3_X branch
branches:
  only:
    - develop
    - master
    - MATH_3_X

after_success:
  - mvn -X clean test jacoco:report coveralls:report
