language: java
sudo: false

jdk:
  - openjdk7
  - oraclejdk8

env:
  - MAVEN_OPTS="-Xmx1028m -XX:MaxPermSize=128m"

## only build master and the MATH_3_X branch
#branches:
#  only:
#    - develop
#    - master
#    - MATH_3_X
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn -Dparallel=classes -Dsurefire.version=2.18.1 -DuseUnlimitedThreads=true -B test

after_success:
  - mvn -X clean test jacoco:report coveralls:report
