language: java
sudo: false

jdk:
  - openjdk7
  - oraclejdk8

#env:
#  - MAVEN_OPTS="-Xmx2056m -XX:MaxPermSize=512m"

## only build master and the MATH_3_X branch
#branches:
#  only:
#    - develop
#    - master
#    - MATH_3_X
install:
  - export MAVEN_OPTS="-Xmx6g -Xms1g -XX:PermSize=2g -XX:MaxPermSize=2g" && mvn -X -B package test

#after_success:
#  - mvn -X clean test jacoco:report coveralls:report
